relation = struct( ...
    'parallel',		0, ...
    'orthogonal', 	1, ...
    'equalAngle', 	2, ...
	'coAxial', 		3, ...
    'coPlanar', 	4, ...
    'equalLength', 	5, ...
    'equalRadius', 	6);

shape = struct( ...
    'plane', 	0, ...
    'sphere', 	1, ...
    'cylinder', 2, ...
    'cone', 	3);
